"use client";

import { useState } from "react";
import {
  getCareerGuidance,
  getCareerRecommendations,
} from "@/lib/api";
import type {
  CareerGuidanceResult,
  CareerRecommendationsResult,
} from "@/lib/api";
import { useRequireAuth } from "@/lib/useAuth";

export default function CareerPage() {
  const { isAuthed } = useRequireAuth();
  const [targetRole, setTargetRole] = useState("");
  const [skillsInput, setSkillsInput] = useState("");
  const [resumeText, setResumeText] = useState("");

  const [recommendations, setRecommendations] =
    useState<CareerRecommendationsResult | null>(null);
  const [guidance, setGuidance] = useState<CareerGuidanceResult | null>(null);

  const [isRecommending, setIsRecommending] = useState(false);
  const [isGuiding, setIsGuiding] = useState(false);
  const [error, setError] = useState("");

  const buildPayload = () => ({
    targetRole: targetRole.trim() || undefined,
    skills: skillsInput
      .split(",")
      .map((skill) => skill.trim())
      .filter(Boolean),
    resumeText: resumeText.trim() || undefined,
  });

  const handleRecommend = async () => {
    setIsRecommending(true);
    setError("");

    try {
      setRecommendations(await getCareerRecommendations(buildPayload()));
    } catch {
      setError("Could not generate recommendations. Please try again.");
    } finally {
      setIsRecommending(false);
    }
  };

  const handleGuidance = async () => {
    setIsGuiding(true);
    setError("");

    try {
      setGuidance(await getCareerGuidance(buildPayload()));
    } catch {
      setError("Could not generate guidance. Please try again.");
    } finally {
      setIsGuiding(false);
    }
  };

  if (!isAuthed) {
    return (
      <main className="app-shell">
        <div className="app-container">
          <p className="mt-8 text-gray-500">Loading career guidance...</p>
        </div>
      </main>
    );
  }

  const fitColor = (score: number) =>
    score >= 70 ? "bg-green-500" : score >= 55 ? "bg-yellow-400" : "bg-red-500";

  return (
    <main className="app-shell">
      <div className="app-container">
        <h1 className="page-heading">Career Guidance</h1>
        <p className="page-subheading">
          Get role recommendations and a personalized skill roadmap based on
          your skills and target role.
        </p>

        {error && <div className="error-box">{error}</div>}

        <section className="card mt-8">
          <h2 className="text-xl font-bold text-slate-900">
            Your profile inputs
          </h2>

          <div className="mt-4 grid gap-4 md:grid-cols-2">
            <div>
              <label className="block text-sm font-semibold text-slate-700">
                Target role (optional)
              </label>
              <input
                type="text"
                value={targetRole}
                onChange={(e) => setTargetRole(e.target.value)}
                placeholder="e.g. Software Engineer"
                className="input-base mt-2"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700">
                Skills (comma-separated)
              </label>
              <input
                type="text"
                value={skillsInput}
                onChange={(e) => setSkillsInput(e.target.value)}
                placeholder="e.g. Python, SQL, React"
                className="input-base mt-2"
              />
            </div>
          </div>

          <div className="mt-4">
            <label className="block text-sm font-semibold text-slate-700">
              Resume text (optional)
            </label>
            <textarea
              value={resumeText}
              onChange={(e) => setResumeText(e.target.value)}
              rows={5}
              placeholder="Paste your resume text for a more tailored analysis..."
              className="input-base mt-2"
            />
          </div>

          <div className="mt-6 flex flex-wrap gap-4">
            <button
              onClick={handleRecommend}
              disabled={isRecommending}
              className="btn-primary"
            >
              {isRecommending ? "Analyzing..." : "Recommend Roles"}
            </button>
            <button
              onClick={handleGuidance}
              disabled={isGuiding}
              className="btn-secondary"
            >
              {isGuiding ? "Generating..." : "Generate AI Guidance"}
            </button>
          </div>

          <p className="mt-4 text-xs text-slate-400">
            Role recommendations are rule-based. AI guidance is generated by an
            LLM and is advisory only.
          </p>
        </section>

        {recommendations && (
          <section className="card mt-8">
            <h2 className="text-xl font-bold text-slate-900">
              Recommended roles
            </h2>

            <div className="mt-6 grid gap-6 md:grid-cols-2">
              {recommendations.recommendations.map((item) => (
                <div
                  key={item.role}
                  className="rounded-xl border border-slate-200 p-5"
                >
                  <div className="flex items-center justify-between gap-3">
                    <h3 className="text-lg font-bold text-slate-900">
                      {item.role}
                    </h3>
                    <span className="rounded-full bg-green-100 px-3 py-1 text-sm font-bold text-green-700">
                      {item.fitScore}% fit
                    </span>
                  </div>

                  <div className="mt-3 h-2 w-full rounded-full bg-slate-200">
                    <div
                      className={`h-2 rounded-full ${fitColor(item.fitScore)}`}
                      style={{ width: `${item.fitScore}%` }}
                    ></div>
                  </div>

                  <p className="mt-5 text-sm font-bold text-slate-700">
                    Skills to learn
                  </p>
                  <div className="mt-2 flex flex-wrap gap-2">
                    {item.skillsToLearn.map((skill) => (
                      <span
                        key={skill}
                        className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-700"
                      >
                        {skill}
                      </span>
                    ))}
                  </div>

                  <p className="mt-5 text-sm font-bold text-slate-700">
                    Interview topics
                  </p>
                  <div className="mt-2 flex flex-wrap gap-2">
                    {item.interviewTopics.map((topic) => (
                      <span
                        key={topic}
                        className="rounded-full bg-purple-100 px-3 py-1 text-xs font-bold text-purple-700"
                      >
                        {topic}
                      </span>
                    ))}
                  </div>

                  <p className="mt-5 text-sm font-bold text-slate-700">
                    Suggested projects
                  </p>
                  <ul className="mt-2 list-disc space-y-1 pl-6 text-sm text-slate-700">
                    {item.suggestedProjects.map((project) => (
                      <li key={project}>{project}</li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>

            {recommendations.extractedSkillSummary && (
              <div className="mt-8 rounded-xl bg-slate-100 p-5">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <h3 className="font-bold text-slate-900">
                    Skill summary from resume
                  </h3>
                  <span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-700">
                    ATS {recommendations.extractedSkillSummary.atsScore}
                  </span>
                </div>
                <div className="mt-3 grid gap-4 md:grid-cols-2">
                  <div>
                    <p className="text-sm font-semibold text-green-700">
                      Found
                    </p>
                    {recommendations.extractedSkillSummary.foundSkills.length >
                    0 ? (
                      <div className="mt-2 flex flex-wrap gap-2">
                        {recommendations.extractedSkillSummary.foundSkills.map(
                          (skill) => (
                            <span
                              key={skill}
                              className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-700"
                            >
                              {skill}
                            </span>
                          )
                        )}
                      </div>
                    ) : (
                      <p className="mt-1 text-sm text-gray-500">
                        No skills detected.
                      </p>
                    )}
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-red-700">
                      Missing
                    </p>
                    {recommendations.extractedSkillSummary.missingSkills.length >
                    0 ? (
                      <div className="mt-2 flex flex-wrap gap-2">
                        {recommendations.extractedSkillSummary.missingSkills.map(
                          (skill) => (
                            <span
                              key={skill}
                              className="rounded-full bg-red-100 px-3 py-1 text-xs font-bold text-red-700"
                            >
                              {skill}
                            </span>
                          )
                        )}
                      </div>
                    ) : (
                      <p className="mt-1 text-sm text-gray-500">
                        Nothing missing.
                      </p>
                    )}
                  </div>
                </div>
              </div>
            )}
          </section>
        )}

        {guidance && (
          <section className="card mt-8">
            <div className="flex items-center justify-between">
              <h2 className="text-xl font-bold text-slate-900">
                AI Career Guidance
              </h2>
              <span className="pill">AI generated</span>
            </div>
            <p className="mt-4 whitespace-pre-wrap leading-7 text-gray-700">
              {guidance.guidance}
            </p>
          </section>
        )}
      </div>
    </main>
  );
}
